title: "浮生日记"
description: "用文字和影像记录生活的温度"
author: "日记主人"
lang: "zh-CN"
timezone: "Asia/Shanghai"

url: "https://xjjjj159.github.io"
baseurl: "/xjjwri"

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "uploads"
    values:
      uploads: true

exclude:
  - Gemfile
  - Gemfile.lock
  - admin/config.yml
  - README.md
  - vendor
